name = "e3nn"
uuid = "1c50a8ea-cbe2-4d3e-83e0-d59f5e8851b3"
authors = ["Deeptendu Santra <deeptendu.santra@protonmail.com> and contributors"]
version = "0.1.0"

[deps]
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
Quaternions = "94ee1d12-ae83-5a48-8b1c-48b8ff168ae0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"

[compat]
julia = "1"
Rotations = "1"
Quaternions = "0.7"
CoordinateTransformations = "0.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
