name = "e3nn"
uuid = "1c50a8ea-cbe2-4d3e-83e0-d59f5e8851b3"
authors = ["Deeptendu Santra <deeptendu.santra@protonmail.com> and contributors"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
